# Nombre de la aplicación
spring.application.name=finant-api

# Base de datos (Supabase PostgreSQL)
spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.vdfwhcmcxucljnlimwpu
spring.datasource.password=nsrfkBkkBKgQMRXe
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Puerto del servidor
server.port=8080

# JWT  ? estas dos líneas son las que faltan o están mal escritas
jwt.secret=finant-clave-secreta-super-larga-para-produccion-2024-minimo-256-bits
jwt.expiration=86400000